config.py.example, py/notifyer.py, requirements.txt
=> fix request using webhookURL

py/notifyer.py
=> forgot to remove

py/notifyer.py
=> fix formatting

py/crawler.py, run.py
https://github.com/takaiyuk/scrape-king-of-time/issues/10
=> Set headless option default as True

run.py
Slackのメッセージを1メッセージにしたんですがどうでしょう？
=> notify in one message

README.md, py/utils/download_chromedriver.py
This pull request supports running in a linux environment.
I checked it working well in my laptop (OS: Ubuntu 18.04).
=> add support for linux

.dockerignore, Dockerfile, README.md, py/crawler.py, run.py
=> Add Dockerfile for local execution

Dockerfile, poetry.lock, py/crawler.py, pyproject.toml
```
$ docker run --rm -it scrape-kot run.py console                                                                                                                      1359ms  金 11/15 14:23:55 2019
残り12営業日: (8/20 日)
あと84.39h必要: (75.21/160h)
貯金: 11.21h
貯金を元に残り営業日の必要勤務時間数を算出すると: 7.02h
2019-11-15の出勤・定時
出勤: 08:37
定時: 17:37
```
できたよ
=> [WIP] Docker

py/crawler.py
ひとまず。URLが変わったかどうかでログイン成功したかどうかを確認する。
https://github.com/takaiyuk/scrape-king-of-time/issues/18
=> Raised exception when login failed

py/crawler.py, py/scraper.py, run.py
打刻にエラーがあるかどうかは `Scraper.get_today_work_start` のみに関わるので有給をとったかどうかはあまりケアする必要はないかも。
https://github.com/takaiyuk/scrape-king-of-time/issues/1 
=> Fix get_today_work_start bug

py/scraper.py
きっと大丈夫！
https://github.com/takaiyuk/scrape-king-of-time/issues/1#issue-522607590
（有給とか半休とか使ったあとに、貯金時間がおかしい！とかのバグが発生したら教えて下さい）
=> Get holiday count

py/scraper.py
https://github.com/takaiyuk/scrape-king-of-time/issues/47
- 33c04b4
https://github.com/takaiyuk/scrape-king-of-time/issues/48
- 0aafbaf
- 5ca28c5
=> Handle month start date error

py/scraper.py, run.py
=> Change notation

console.sh, notify.sh, py/scraper.py, py/utils/download_chromedriver.py
貯金時間がマイナスのときのバグの修正。
修正前
```
>>> from py.scraper import Scraper
>>> Scraper().calc_saving_time(work_hour=40, work_count=5)
0.0  # work_hour: 働いた時間, work_count: 働いた日数
>>> Scraper().calc_saving_time(work_hour=43.25, work_count=5)
3.25  # 3時間25分
>>> Scraper().calc_saving_time(work_hour=38.25, work_count=5)
-1.75  # 本当は-1.35（1時間35分不足）を期待
```
修正後
```
>>> from py.scraper import Scraper
>>> Scraper().calc_saving_time(work_hour=40, work_count=5)
0.0
>>> Scraper().calc_saving_time(work_hour=43.25, work_count=5)
3.25
>>> Scraper().calc_saving_time(work_hour=38.25, work_count=5)
-1.35
```
=> Fix scraper

py/scraper.py, py/tests/test_scraper.py
https://github.com/takaiyuk/scrape-king-of-time/issues/64
修正前
```
$ ./console.sh
残り1.0営業日: (19.0/20.0 日)
あと1時間1分必要: (158時間5分/160時間0分)
貯金: 6時間5分
貯金を元に残り営業日の必要勤務時間数を算出すると: 1時間1分
```
修正後
```
$ python run.py console
残り1.0営業日: (19.0/20.0 日)
あと1時間10分必要: (158時間50分/160時間00分)
貯金: 6時間50分
貯金を元に残り営業日の必要勤務時間数を算出すると: 1時間10分
```
=> Fix get your work hour

.github/workflows/dockerimage.yml, build.sh, push.sh
=> Add GitHub action

README.md, console.sh, notify.sh
#74 の対応
デフォルトをhome以下の `.scrape_kot` ディレクトリを参照し、なければカレントディレクトリを見る。
既存のも動くように対応
=> default setting using homedir

Dockerfile, run.py, scrapekot.sh
https://github.com/takaiyuk/scrape-king-of-time/issues/79
こんな感じですか？（デフォルト値を設定したほうがいいのか？）
=> add-argument-to-sh

.gitignore, Dockerfile, README.md, my_recorder/const.py, my_recorder/crawler.py, my_recorder/run.py, myrecoder-py.sh, myrecoder.sh
My Recorder から叩けるようにした。
（本当に打刻出来ているかかどうかは各自で要確認でお願いします）
=> My Recorder

my_recorder/run.py
=> Add more sec after browser.get

README.md, my_recorder/run.py, myrecoder-py.sh, myrecoder.sh
myrecorder(-py).sh でプロンプトをスキップする
cf.) #87
=> Yes argument option

.github/workflows/dockerimage.yml, my_recorder/run.py
master -> latest
develop -> stg
その他 -> dev
のタグを貼って、全ブランチでBuild&Pushする
=> Fix workflow

my_recorder/run.py
sleep 入れないとブラウザの更新が追いつかず、 `NoSuchElementException` 出るっぽいので
=> Add sleep when yes

Dockerfile, py/scraper.py, py/tests/test_scraper.py
https://github.com/takaiyuk/scrape-king-of-time/issues/103
=> Handle error occurred when monthly_work_hour is zero

Dockerfile, config.py.example, my_recorder/const.py, my_recorder/run.py
myrecorder で打刻する時、指定したチャンネルに関連するスタンプのメッセージを送信するよう修正。例えば出勤時 打刻の際に同時に特定チャンネルに :shukkin: スタンプを送信する。
=> Notify when myrecorder punch

README.md, config.py.example
Reverts takaiyuk/scrape-king-of-time#113
=> Revert "Change README"

README.md, config.py.example
Reverts takaiyuk/scrape-king-of-time#114
=> Revert "Revert "Change README""

Dockerfile, README.md, my_recorder/const.py, my_recorder/run.py, myrecorder.sh, shell/myrecorder-py.sh
https://github.com/takaiyuk/scrape-king-of-time/issues/117
出退勤時のメッセージを引数で指定できるようにした。
デフォルトではいくつかの候補からランダムに選択するようにした。
デフォルトのメッセージは[ココを参照](https://github.com/takaiyuk/scrape-king-of-time/commit/1ae66b8094c57478d79a0982dce00732b3f8b582#diff-b24887f0662ebbe985378118bbe83655R16-R26)
=> Random kintai message

config.py.example, my_recorder/run.py
can set icon emoji and user name
=> be able to set user

Dockerfile
=> Use slim as base image

Dockerfile
Reverts takaiyuk/scrape-king-of-time#126
chrome が動かなかったのでリバート
=> Revert "Add libgconf2-4"

Dockerfile
Reverts takaiyuk/scrape-king-of-time#124
chrome が動かなかったのでリバート
=> Revert "Use slim as base image"

Dockerfile
=> Copy only site-packages

my_recorder/run.py
Change attachment to text
Using attachment add new lines, so change to text field.
=> change attachment to text

requirements.txt
Same issue with https://github.com/tiangolo/typer/issues/377
=> Fix click==8.0.4

kot/common/notify.py, kot/myrecorder/notify.py, kot/scrapekot/notify.py, tests/myrecorder/test_notify.py
myrecorder で no を打っても通知されてしまう（打刻はスキップされるが）
=> Skip notification when params.yes is False

.github/workflows/dockerimage.yml
Same as https://github.com/takaiyuk/kot/pull/182
=> Skip push image for dependabot

docker-compose.yml, docker/kot/Dockerfile, kot/__main__.py, kot/common/crawl.py, kot/service.py
Add remote browser for arm like M1 Mac
run with
```
$ docker compose run --rm app
or
$ docker compose run --rm app kot scrape --console --browser-kind remote
```
=> with remote browser

kot/myrecorder/__init__.py
=> Add myrecorder messages

compose.yml
起動後少し待たないと seleniumがクラッシュしてしまうので start_periodを設定しました
=> set start period

kot/common/crawl.py
option を色々足すとクラッシュが起きにくくなった気がする
=> Add options for remote

README.md, docs/migration-guide-for-v3.1.0.md
https://github.com/takaiyuk/kot/blob/38937fbff3a631652d1d072ffe6c7d18c984342b/docs/migration-guide-for-v3.1.0.md
=> Add migration guide for v3.1.0

compose.yml, pyproject.toml
fix for poetry build
https://python-poetry.org/docs/pyproject#package-mode
and unneccesary versions for docker compose v2
https://zenn.dev/harpseal/articles/8dc2602ffe3365
=> set package mode for poetry 2.0
